# Generated by Django 6.0.3 on 2026-03-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='musicafavorita',
            name='duracao_ms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='musicafavorita',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
