# Generated by Django 6.0.3 on 2026-03-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='spotify_id',
            new_name='lastfm_id',
        ),
        migrations.RenameField(
            model_name='musicafavorita',
            old_name='spotify_id',
            new_name='lastfm_id',
        ),
    ]
