# Generated by Django 6.0.3 on 2026-03-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_spotify_id_artista_lastfm_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='descricao',
        ),
    ]
